/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/DientamoebaFragilisTrophozoite-v1.glb -o src/components/DientamoebaFragilis/DFTrophozoite.jsx -k -r public 
*/

import React, { useEffect, useMemo } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import DFOuterMembraneMaterial from "./shaders/DFOuterMembraneMaterial";
import { createDFMaterials } from "./DFMaterials";

export function DFTrophozoite(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/DientamoebaFragilisTrophozoite-v1.glb",
  );
  const { actions } = useAnimations(animations, group);
  // console.log(actions);

  const {
    nucleusMaterial,
    karyosomeMaterial,
    spindleMaterial,
    vacuoleMaterial,
    foodBodyMaterial,
    golgiMaterial,
    granuleMaterial,
    innerMembraneMaterial,
  } = useMemo(() => createDFMaterials(), []);

  useEffect(() => {
    const actionNames = ["SphereAction", "SphereAction.001"];

    actionNames.forEach((name) => {
      const action = actions?.[name];
      if (action) {
        action.reset().fadeIn(0.5).play();
        console.log(`Animation found: ${name}`);
      } else {
        console.warn(`Animation not found: ${name}`);
      }
    });

    return () => {
      actionNames.forEach((name) => actions?.[name]?.fadeOut(0.5));
    };
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Nucleus1"
          geometry={nodes.Nucleus1.geometry}
          material={nucleusMaterial}
          position={[0, 0.873, 0.251]}
        />
        <mesh
          name="Icosphere006"
          geometry={nodes.Icosphere006.geometry}
          material={karyosomeMaterial}
          position={[-0.006, 0.879, 0.246]}
          rotation={[0.27, -0.424, 0.113]}
        />
        <mesh
          name="Nucleus2"
          geometry={nodes.Nucleus2.geometry}
          material={nucleusMaterial}
          position={[0, 1.141, -0.351]}
        />
        <mesh
          name="Icosphere001"
          geometry={nodes.Icosphere001.geometry}
          material={karyosomeMaterial}
          position={[-0.006, 1.147, -0.356]}
          rotation={[0.27, -0.424, 0.113]}
        />

        <mesh
          name="Spindle5"
          geometry={nodes.Spindle5.geometry}
          material={spindleMaterial}
          position={[0, 0.88, -0.084]}
          rotation={[2.256, 0, 0]}
        />
        <mesh
          name="Spindle4"
          geometry={nodes.Spindle4.geometry}
          material={spindleMaterial}
          position={[0, 0.929, -0.084]}
          rotation={[2.256, 0, 0]}
        />
        <mesh
          name="Spindle3"
          geometry={nodes.Spindle3.geometry}
          material={spindleMaterial}
          position={[0, 0.96, -0.052]}
          rotation={[2.256, 0, 0]}
        />
        <mesh
          name="Spindle2"
          geometry={nodes.Spindle2.geometry}
          material={spindleMaterial}
          position={[0, 1.026, -0.052]}
          rotation={[2.256, 0, 0]}
        />
        <mesh
          name="Spindle1"
          geometry={nodes.Spindle1.geometry}
          material={spindleMaterial}
          position={[0, 1.086, -0.034]}
          rotation={[2.256, 0, 0]}
        />

        <mesh
          name="vacuole1"
          geometry={nodes.vacuole1.geometry}
          material={vacuoleMaterial}
          position={[0.099, 0.555, -0.245]}
        />
        <mesh
          name="vacuole2"
          geometry={nodes.vacuole2.geometry}
          material={vacuoleMaterial}
          position={[-0.259, 1.466, 0.197]}
        />
        <mesh
          name="vacuole3"
          geometry={nodes.vacuole3.geometry}
          material={vacuoleMaterial}
          position={[-0.337, 0.582, 0.36]}
        />

        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={foodBodyMaterial}
          position={[0.099, 0.555, -0.206]}
          rotation={[2.122, 1.247, -1.635]}
        />
        <mesh
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={foodBodyMaterial}
          position={[0.099, 0.555, -0.323]}
          rotation={[-1.168, 1.064, 0.898]}
        />
        <mesh
          name="Cube002"
          geometry={nodes.Cube002.geometry}
          material={foodBodyMaterial}
          position={[0.018, 0.589, -0.246]}
          rotation={[-1.168, 1.064, 0.898]}
        />
        <mesh
          name="Icosphere"
          geometry={nodes.Icosphere.geometry}
          material={foodBodyMaterial}
          position={[0.122, 0.479, -0.274]}
        />
        <mesh
          name="Icosphere002"
          geometry={nodes.Icosphere002.geometry}
          material={foodBodyMaterial}
          position={[0.129, 0.469, -0.215]}
        />

        <mesh
          name="Cube003"
          geometry={nodes.Cube003.geometry}
          material={foodBodyMaterial}
          position={[-0.259, 1.466, 0.236]}
          rotation={[2.122, 1.247, -1.635]}
        />
        <mesh
          name="Cube004"
          geometry={nodes.Cube004.geometry}
          material={foodBodyMaterial}
          position={[-0.259, 1.466, 0.119]}
          rotation={[-1.168, 1.064, 0.898]}
        />
        <mesh
          name="Cube005"
          geometry={nodes.Cube005.geometry}
          material={foodBodyMaterial}
          position={[-0.34, 1.501, 0.195]}
          rotation={[-1.168, 1.064, 0.898]}
        />
        <mesh
          name="Icosphere003"
          geometry={nodes.Icosphere003.geometry}
          material={foodBodyMaterial}
          position={[-0.236, 1.391, 0.167]}
        />
        <mesh
          name="Icosphere004"
          geometry={nodes.Icosphere004.geometry}
          material={foodBodyMaterial}
          position={[-0.229, 1.38, 0.227]}
        />

        <mesh
          name="Cube006"
          geometry={nodes.Cube006.geometry}
          material={foodBodyMaterial}
          position={[-0.337, 0.582, 0.399]}
          rotation={[2.122, 1.247, -1.635]}
        />
        <mesh
          name="Cube007"
          geometry={nodes.Cube007.geometry}
          material={foodBodyMaterial}
          position={[-0.337, 0.582, 0.281]}
          rotation={[-1.168, 1.064, 0.898]}
        />
        <mesh
          name="Cube008"
          geometry={nodes.Cube008.geometry}
          material={foodBodyMaterial}
          position={[-0.417, 0.616, 0.358]}
          rotation={[-1.168, 1.064, 0.898]}
        />
        <mesh
          name="Icosphere005"
          geometry={nodes.Icosphere005.geometry}
          material={foodBodyMaterial}
          position={[-0.313, 0.506, 0.33]}
        />
        <mesh
          name="Icosphere007"
          geometry={nodes.Icosphere007.geometry}
          material={foodBodyMaterial}
          position={[-0.306, 0.496, 0.39]}
        />
        <mesh
          name="Icosphere008"
          geometry={nodes.Icosphere008.geometry}
          material={foodBodyMaterial}
          position={[-0.228, 0.548, 0.357]}
        />
        <mesh
          name="Cube009"
          geometry={nodes.Cube009.geometry}
          material={foodBodyMaterial}
          position={[-0.159, 1.455, 0.191]}
          rotation={[-1.168, 1.064, 0.898]}
        />

        <mesh
          name="golgi4"
          geometry={nodes.golgi4.geometry}
          material={golgiMaterial}
          position={[-0.213, 0.788, -0.59]}
          rotation={[0.544, 1.547, 0]}
        />
        <mesh
          name="golgi5"
          geometry={nodes.golgi5.geometry}
          material={golgiMaterial}
          position={[-0.213, 0.818, -0.572]}
          rotation={[0.544, 1.547, 0]}
        />
        <mesh
          name="golgi6"
          geometry={nodes.golgi6.geometry}
          material={golgiMaterial}
          position={[-0.213, 0.847, -0.554]}
          rotation={[0.544, 1.547, 0]}
        />
        <mesh
          name="golgi3"
          geometry={nodes.golgi3.geometry}
          material={golgiMaterial}
          position={[-0.213, 0.743, -0.598]}
          rotation={[0.544, 1.547, 0]}
        />
        <mesh
          name="golgi2"
          geometry={nodes.golgi2.geometry}
          material={golgiMaterial}
          position={[-0.213, 0.713, -0.617]}
          rotation={[0.544, 1.547, 0]}
        />
        <mesh
          name="gogli1"
          geometry={nodes.gogli1.geometry}
          material={golgiMaterial}
          position={[-0.213, 0.68, -0.636]}
          rotation={[0.544, 1.547, 0]}
        />

        <mesh
          name="granules"
          geometry={nodes.granules.geometry}
          material={granuleMaterial}
          position={[-0.001, 1.032, -0.07]}
          rotation={[2.942, -0.916, -Math.PI / 2]}
        />
        <mesh
          name="Outer_Membrane"
          geometry={nodes.Outer_Membrane.geometry}
          // material={nodes.Outer_Membrane.material}
          morphTargetDictionary={nodes.Outer_Membrane.morphTargetDictionary}
          morphTargetInfluences={nodes.Outer_Membrane.morphTargetInfluences}
          position={[0, 1, 0]}
        >
          <DFOuterMembraneMaterial
            opacity={0.74}
            baseColor="#3b490d"
            shadowColor="#000000"
            membraneTint="#404332"
            noiseScale={5.4}
            flowSpeed={10.12}
            brightness={0.05}
            granuleStrength={0.38}
            fresnelStrength={0.0}
            rimStrength={2.16}
            wobbleStrength={0.012}
            wobbleSpeed={0.42}
            morphTargets
          />
        </mesh>
        <mesh
          name="Inner_Membrane"
          geometry={nodes.Inner_Membrane.geometry}
          material={innerMembraneMaterial}
          morphTargetDictionary={nodes.Inner_Membrane.morphTargetDictionary}
          morphTargetInfluences={nodes.Inner_Membrane.morphTargetInfluences}
          position={[0, 1, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/DientamoebaFragilisTrophozoite-v1.glb");
