/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/GLTrophozoite-v1.glb -o src/components/GiardiaLamblia/GLTrophozoite.jsx -k -r public 
*/

import React, { useEffect, useMemo } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import CytoplasmMaterialImpl from "./Shaders/CytoplasmMaterial";
import * as THREE from "three";
import { createGiardiaMaterials } from "./Shaders/GLMaterials";

export function GLTrophozoite(props) {
  const group = React.useRef();
  const { nodes, _materials, animations } = useGLTF(
    "/models/GLTrophozoite-v1.glb",
  );
  const { actions } = useAnimations(animations, group);
  console.log("trophozoite");

  const {
    nucleusMaterial,
    karyosomeMaterial,
    kinetosomeMaterial,
    medianBodyMaterial,
    flagellumMaterial,
  } = useMemo(() => createGiardiaMaterials(), []);

  useEffect(() => {
    const actionNames = [
      "BézierCurveAction",
      "BézierCurve.001Action",
      "BézierCurve.002Action",
      "BézierCurve.003Action",
      "BézierCurve.004Action",
      "BézierCurve.005Action",
      "BézierCurve.006Action",
      "BézierCurve.007Action",
      "BézierCurve.008Action",
    ];

    actionNames.forEach((name) => {
      const action = actions?.[name];
      if (action) {
        action.reset().fadeIn(0.5).play();
        console.log(`Animation found: ${name}`);
      } else {
        console.warn(`Animation not found: ${name}`);
      }
    });

    return () => {
      actionNames.forEach((name) => actions?.[name]?.fadeOut(0.5));
    };
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Body"
          geometry={nodes.Body.geometry}
          material={nodes.Body.material}
          position={[0, 2.23, -2.932]}
        >
          <CytoplasmMaterialImpl
            opacity={0.44}
            color="#71a3b3"
            shadowColor="#374c52"
            noiseScale={7.2}
            flowSpeed={1.82}
            brightness={0.16}
            fresnelStrength={1.12}
            thickness={0.9}
            wobbleStrength={0.105}
            wobbleSpeed={0.8}
            morphTargets
          />
        </mesh>
        <mesh
          name="Nucleus1"
          geometry={nodes.Nucleus1.geometry}
          material={nucleusMaterial}
          position={[-0.063, 2.407, -3.524]}
        />
        <mesh
          name="Nucleus2"
          geometry={nodes.Nucleus2.geometry}
          material={nucleusMaterial}
          position={[-0.063, 2.407, -2.272]}
        />

        <mesh
          name="Karyosome1"
          geometry={nodes.Karyosome1.geometry}
          material={karyosomeMaterial}
          position={[-0.063, 2.407, -3.524]}
        />
        <mesh
          name="Karyosome2"
          geometry={nodes.Karyosome2.geometry}
          material={karyosomeMaterial}
          position={[-0.063, 2.407, -2.133]}
        />

        <mesh
          name="Kinetosome1"
          geometry={nodes.Kinetosome1.geometry}
          material={kinetosomeMaterial}
          position={[-0.063, 2.812, -3.196]}
        />
        <mesh
          name="Kinetosome2"
          geometry={nodes.Kinetosome2.geometry}
          material={kinetosomeMaterial}
          position={[-0.063, 2.816, -2.602]}
        />
        <mesh
          name="Kinetosome6"
          geometry={nodes.Kinetosome6.geometry}
          material={kinetosomeMaterial}
          position={[-0.028, 2.609, -2.905]}
        />
        <mesh
          name="Kinetosome5"
          geometry={nodes.Kinetosome5.geometry}
          material={kinetosomeMaterial}
          position={[-0.007, 2.604, -2.978]}
        />
        <mesh
          name="Kinetosome8"
          geometry={nodes.Kinetosome8.geometry}
          material={kinetosomeMaterial}
          position={[-0.176, 2.438, -2.886]}
          scale={1.245}
        />
        <mesh
          name="Kinetosome3"
          geometry={nodes.Kinetosome3.geometry}
          material={kinetosomeMaterial}
          position={[-0.063, 2.783, -2.96]}
        />
        <mesh
          name="Kinetosome4"
          geometry={nodes.Kinetosome4.geometry}
          material={kinetosomeMaterial}
          position={[-0.063, 2.776, -2.868]}
        />
        <mesh
          name="Kinetosome7"
          geometry={nodes.Kinetosome7.geometry}
          material={kinetosomeMaterial}
          position={[-0.192, 2.425, -2.982]}
        />

        <mesh
          name="medianbody1"
          geometry={nodes.medianbody1.geometry}
          material={medianBodyMaterial}
          position={[-0.028, 1.619, -2.965]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          name="medianbody2"
          geometry={nodes.medianbody2.geometry}
          material={medianBodyMaterial}
          position={[-0.028, 1.39, -2.965]}
          rotation={[0, 0, -Math.PI / 2]}
        />

        <mesh
          name="anterirorflagellum1"
          geometry={nodes.anterirorflagellum1.geometry}
          material={flagellumMaterial}
          morphTargetDictionary={
            nodes.anterirorflagellum1.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.anterirorflagellum1.morphTargetInfluences
          }
          position={[0.047, 2.833, -3.206]}
          rotation={[Math.PI, 0, Math.PI / 2]}
        />
        <mesh
          name="anterirorflagellum2"
          geometry={nodes.anterirorflagellum2.geometry}
          material={flagellumMaterial}
          morphTargetDictionary={
            nodes.anterirorflagellum2.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.anterirorflagellum2.morphTargetInfluences
          }
          position={[-0.17, 2.801, -2.595]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          name="posteriorflagellum1"
          geometry={nodes.posteriorflagellum1.geometry}
          material={flagellumMaterial}
          morphTargetDictionary={
            nodes.posteriorflagellum1.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.posteriorflagellum1.morphTargetInfluences
          }
          position={[0.047, 2.809, -3.566]}
          rotation={[Math.PI, 0, Math.PI / 2]}
        />
        <mesh
          name="posteriorflagellum2"
          geometry={nodes.posteriorflagellum2.geometry}
          material={flagellumMaterial}
          morphTargetDictionary={
            nodes.posteriorflagellum2.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.posteriorflagellum2.morphTargetInfluences
          }
          position={[-0.178, 2.818, -2.259]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          name="caudalflagellum1"
          geometry={nodes.caudalflagellum1.geometry}
          material={flagellumMaterial}
          morphTargetDictionary={nodes.caudalflagellum1.morphTargetDictionary}
          morphTargetInfluences={nodes.caudalflagellum1.morphTargetInfluences}
          position={[0.104, 2.641, -3.586]}
          rotation={[Math.PI, 0, Math.PI / 2]}
        />
        <mesh
          name="caudalflagellum2"
          geometry={nodes.caudalflagellum2.geometry}
          material={flagellumMaterial}
          morphTargetDictionary={nodes.caudalflagellum2.morphTargetDictionary}
          morphTargetInfluences={nodes.caudalflagellum2.morphTargetInfluences}
          position={[0.104, 2.641, -3.503]}
          rotation={[Math.PI, 0, Math.PI / 2]}
        />
        <mesh
          name="ventralflagellum1"
          geometry={nodes.ventralflagellum1.geometry}
          material={flagellumMaterial}
          morphTargetDictionary={nodes.ventralflagellum1.morphTargetDictionary}
          morphTargetInfluences={nodes.ventralflagellum1.morphTargetInfluences}
          position={[-0.305, 2.461, -2.372]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          name="ventralflagellum2"
          geometry={nodes.ventralflagellum2.geometry}
          material={flagellumMaterial}
          morphTargetDictionary={nodes.ventralflagellum2.morphTargetDictionary}
          morphTargetInfluences={nodes.ventralflagellum2.morphTargetInfluences}
          position={[-0.412, 1.073, -2.921]}
          rotation={[0, 0, -Math.PI / 2]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/GLTrophozoite-v1.glb");
