/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/EntHistCyst-v1.glb -o src/components/EntamoebaHystolytica/Cyst/EntHistCyst.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/EntHistCyst-v1.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="outer_cyst_membrane"
        geometry={nodes.outer_cyst_membrane.geometry}
        material={nodes.outer_cyst_membrane.material}
        position={[0, 1, 0]}
      />
      <mesh
        name="inner_cyst_membrane"
        geometry={nodes.inner_cyst_membrane.geometry}
        material={nodes.inner_cyst_membrane.material}
      />
      <mesh
        name="chromatoid_body_1"
        geometry={nodes.chromatoid_body_1.geometry}
        material={nodes.chromatoid_body_1.material}
        position={[-0.405, 1.449, -0.206]}
        rotation={[0, 0, -0.977]}
      />
      <mesh
        name="chromatoid_body_2"
        geometry={nodes.chromatoid_body_2.geometry}
        material={nodes.chromatoid_body_2.material}
        position={[0.523, 0.681, 0.023]}
        rotation={[0, 0, -0.396]}
      />
      <mesh
        name="chromatoid_body_3"
        geometry={nodes.chromatoid_body_3.geometry}
        material={nodes.chromatoid_body_3.material}
        position={[-0.476, 0.839, -0.389]}
        rotation={[-1.186, 0.034, -0.581]}
      />
      <mesh
        name="nuclear_envelope"
        geometry={nodes.nuclear_envelope.geometry}
        material={nodes.nuclear_envelope.material}
        position={[0, 0.772, 0.4]}
      />
      <mesh
        name="karyosome"
        geometry={nodes.karyosome.geometry}
        material={nodes.karyosome.material}
        position={[0, 0.772, 0.4]}
      />
      <mesh
        name="chromatin_layer"
        geometry={nodes.chromatin_layer.geometry}
        material={nodes.chromatin_layer.material}
        position={[0, 0.772, 0.4]}
      />
      <mesh
        name="nuclear_envelope001"
        geometry={nodes.nuclear_envelope001.geometry}
        material={nodes.nuclear_envelope001.material}
        position={[0.094, 1.45, 0.27]}
      />
      <mesh
        name="karyosome001"
        geometry={nodes.karyosome001.geometry}
        material={nodes.karyosome001.material}
        position={[0.094, 1.45, 0.27]}
      />
      <mesh
        name="chromatin_layer001"
        geometry={nodes.chromatin_layer001.geometry}
        material={nodes.chromatin_layer001.material}
        position={[0.094, 1.45, 0.27]}
      />
      <mesh
        name="nuclear_envelope002"
        geometry={nodes.nuclear_envelope002.geometry}
        material={nodes.nuclear_envelope002.material}
        position={[0, 1.066, -0.222]}
      />
      <mesh
        name="karyosome002"
        geometry={nodes.karyosome002.geometry}
        material={nodes.karyosome002.material}
        position={[0, 1.066, -0.222]}
      />
      <mesh
        name="chromatin_layer002"
        geometry={nodes.chromatin_layer002.geometry}
        material={nodes.chromatin_layer002.material}
        position={[0, 1.066, -0.222]}
      />
      <mesh
        name="nuclear_envelope003"
        geometry={nodes.nuclear_envelope003.geometry}
        material={nodes.nuclear_envelope003.material}
        position={[0.015, 0.575, -0.262]}
      />
      <mesh
        name="karyosome003"
        geometry={nodes.karyosome003.geometry}
        material={nodes.karyosome003.material}
        position={[0.015, 0.575, -0.262]}
      />
      <mesh
        name="chromatin_layer003"
        geometry={nodes.chromatin_layer003.geometry}
        material={nodes.chromatin_layer003.material}
        position={[0.015, 0.575, -0.262]}
      />
    </group>
  );
}

useGLTF.preload("/models/EntHistCyst-v1.glb");
