/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/BlastoCystisCyst-v1.glb -o src/components/BlastoCystis/Cyst/BCCyst.jsx -k -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/BlastoCystisCyst-v1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="CystMLO1" geometry={nodes.CystMLO1.geometry} material={nodes.CystMLO1.material} position={[-3.833, 0.676, -0.349]} rotation={[-0.086, -0.468, -0.133]} scale={[0.082, 0.132, 0.066]} />
      <mesh name="CystMLO2" geometry={nodes.CystMLO2.geometry} material={nodes.CystMLO2.material} position={[-3.324, 1.076, -0.355]} rotation={[-3.035, 0.767, 2.974]} scale={[0.082, 0.132, 0.066]} />
      <mesh name="CystMLO3" geometry={nodes.CystMLO3.geometry} material={nodes.CystMLO3.material} position={[-3.706, 0.9, 0.311]} rotation={[-0.167, 0.06, -1.056]} scale={[0.082, 0.132, 0.066]} />
      <mesh name="CystBody" geometry={nodes.CystBody.geometry} material={nodes.CystBody.material} position={[-3.819, 1, 0]} />
      <mesh name="Cytoplasm" geometry={nodes.Cytoplasm.geometry} material={nodes.Cytoplasm.material} position={[-3.819, 1, 0]} scale={0.832} />
      <mesh name="CystNucleus1" geometry={nodes.CystNucleus1.geometry} material={nodes.CystNucleus1.material} position={[-3.652, 1.323, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.102, 0.099, 0.198]} />
      <mesh name="CystNucleus3" geometry={nodes.CystNucleus3.geometry} material={nodes.CystNucleus3.material} position={[-4.251, 1.141, 0]} rotation={[-0.79, 0.183, -1.702]} scale={[0.102, 0.099, 0.198]} />
      <mesh name="CystNucleus2" geometry={nodes.CystNucleus2.geometry} material={nodes.CystNucleus2.material} position={[-3.979, 1.505, 0.155]} rotation={[-1.758, 0.001, 0.056]} scale={[0.102, 0.099, 0.198]} />
      <mesh name="CystNucleus4" geometry={nodes.CystNucleus4.geometry} material={nodes.CystNucleus4.material} position={[-3.975, 0.955, -0.125]} rotation={[0.828, -1.11, 0.631]} scale={[0.102, 0.099, 0.198]} />
      <mesh name="StorageGranules" geometry={nodes.StorageGranules.geometry} material={nodes.StorageGranules.material} position={[-3.809, 0.994, 0.013]} rotation={[0.333, 0.794, -Math.PI / 2]} scale={0.029} />
    </group>
  )
}

useGLTF.preload('/models/BlastoCystisCyst-v1.glb')
