/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/EColiBody-v1.glb -o src/components/EntamoebaColi/EColiBody2.jsx -k -r public 
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { DirtyCytoplasmMaterial } from "./DirtyCytoplasmShader";
import { EColiNucleus } from "./EColiNucleus";
import { EColiVacuolesWRBC } from "./EColiVacuolesWRBC";
import { EColiVacuolesWBacteria } from "./EColiVacuolesWBacteria";

export function EColiModel2(props) {
  const group = React.useRef();
  const { nodes, _materials, animations } = useGLTF("/models/EColiBody-v1.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    const actionNames = ["MeshAction", "MeshAction.001"];

    actionNames.forEach((name) => {
      const action = actions?.[name];
      if (action) {
        action.reset().fadeIn(0.5).play();
        console.log(`Animation found: ${name}`);
      } else {
        console.warn(`Animation not found: ${name}`);
      }
    });

    return () => {
      actionNames.forEach((name) => actions?.[name]?.fadeOut(0.5));
    };
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        {/* NUCLEUS */}
        <EColiNucleus
          position={[0, 0.8, 0]}
          scale={0.25}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="outermembrane"
          geometry={nodes.outermembrane.geometry}
          // material={nodes.outermembrane.material}
          morphTargetDictionary={nodes.outermembrane.morphTargetDictionary}
          morphTargetInfluences={nodes.outermembrane.morphTargetInfluences}
          position={[0, 1, 0]}
        >
          <meshPhysicalMaterial
            morphTargets={true}
            color={"#c2cf75"}
            transparent={true}
            opacity={0.8}
            transmission={0.1}
            thickness={1.0}
            roughness={0.2}
            metalness={0}
            ior={1.33}
            depthWrite={false}
          />
        </mesh>
        <mesh
          name="innermembranecytopasm"
          geometry={nodes.innermembranecytopasm.geometry}
          // material={nodes.innermembranecytopasm.material}
          morphTargetDictionary={
            nodes.innermembranecytopasm.morphTargetDictionary
          }
          morphTargetInfluences={
            nodes.innermembranecytopasm.morphTargetInfluences
          }
          position={[0, 1, 0]}
        >
          <DirtyCytoplasmMaterial
            opacity={0.38}
            noiseScale={13.0}
            flowSpeed={0.96}
            brightness={0.2}
            color="#c2cf75"
            fresnelStrength={0.06}
            morphTargets={true}
          />
        </mesh>

        {/* EMPTY FOOD VACUOLES */}
        <group name="Vacuoles">
          <EColiVacuolesWBacteria position={[0.5, 1.2, 0.3]} scale={0.15} />
          {/* <EColiVacuolesWBacteria
            position={[-0.4, 1.3, 0.2]}
            scale={0.12}
            rotation={[1, 0, 0.5]}
          />
          <EColiVacuolesWBacteria position={[-0.1, 1.0, -0.5]} scale={0.18} />
          <EColiVacuolesWBacteria position={[0.7, 0.8, -0.7]} scale={0.11} />
          <EColiVacuolesWBacteria position={[-0.8, 1.2, 0.1]} scale={0.05} />
          <EColiVacuolesWBacteria
            position={[0.4, 0.7, -0.2]}
            scale={0.04}
            rotation={[1, 0, 0.5]}
          />
          <EColiVacuolesWBacteria position={[0.6, 0.7, -0.2]} scale={0.04} />
          <EColiVacuolesWBacteria position={[0.1, 0.7, 0.7]} scale={0.08} /> */}

          <EColiVacuolesWRBC
            position={[-0.24, 0.5, 0.02]}
            scale={0.13}
            rotation={[1, 0, 0.5]}
          />
          {/* <EColiVacuolesWRBC
            position={[0.14, 0.7, -0.22]}
            scale={0.14}
            rotation={[1, 0, 0.5]}
          />
          <EColiVacuolesWRBC
            position={[-0.68, 1.1, -0.22]}
            scale={0.13}
            rotation={[1, 0, 0.5]}
          /> */}
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/EColiBody-v1.glb");
