/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/EColiBody-v1.glb -o src/components/EntamoebaColi/EColiBody.jsx -k -r public 
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { DirtyCytoplasmMaterial } from "./DirtyCytoplasmShader";

export function EColiModel(props) {
  const group = React.useRef();
  const { nodes, _materials, animations } = useGLTF("/models/EColiBody-v1.glb");
  const { actions } = useAnimations(animations, group);
  // console.log(actions);

  useEffect(() => {
    const actionNames = ["MeshAction", "MeshAction.001"];

    actionNames.forEach((name) => {
      const action = actions?.[name];
      if (action) {
        action.reset().fadeIn(0.5).play();
      } else {
        console.warn(`Animation not found: ${name}`);
      }
    });

    return () => {
      actionNames.forEach((name) => actions?.[name]?.fadeOut(0.5));
    };
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="innermembrane"
          geometry={nodes.Mball002.geometry}
          // material={nodes.Mball002.material}
          morphTargetDictionary={nodes.Mball002.morphTargetDictionary}
          morphTargetInfluences={nodes.Mball002.morphTargetInfluences}
          position={[0, 1, 0]}
        >
          <DirtyCytoplasmMaterial
            color="#9a8862"
            opacity={0.88}
            scale={3.4}
            contrast={1.25}
            brightness={1.0}
            wobble={0.012}
            rimStrength={0.35}
            darkness={0.45}
          />
        </mesh>
        {/* <mesh
          name="outermembrane"
          geometry={nodes.Mball001.geometry}
          material={nodes.Mball001.material}
          morphTargetDictionary={nodes.Mball001.morphTargetDictionary}
          morphTargetInfluences={nodes.Mball001.morphTargetInfluences}
          position={[0, 1, 0]}
        >
          <meshPhysicalMaterial
            color={"#cceed3"}
            transparent={true}
            opacity={0.8}
            transmission={0.1}
            thickness={1.0}
            roughness={0.2}
            metalness={0}
            ior={1.33}
            depthWrite={false}
          />
        </mesh> */}
      </group>
    </group>
  );
}

useGLTF.preload("/models/EColiBody-v1.glb");
