/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/BlastoCystisVacuole-v1.glb -o src/components/BlastoCystis/BCVacuole.jsx -k -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/BlastoCystisVacuole-v1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Outer_Membrane" geometry={nodes.Outer_Membrane.geometry} material={nodes.Outer_Membrane.material} position={[0, 1, 0]} />
      <mesh name="Inner_Membrane" geometry={nodes.Inner_Membrane.geometry} material={nodes.Inner_Membrane.material} position={[0, 1, 0]} />
      <mesh name="Vacuole" geometry={nodes.Vacuole.geometry} material={nodes.Vacuole.material} position={[0, 1, 0]} />
      <mesh name="Nucleus3" geometry={nodes.Nucleus3.geometry} material={nodes.Nucleus3.material} position={[0.012, 1, 0.828]} rotation={[0, 0, 0.89]} />
      <mesh name="Nucleus4" geometry={nodes.Nucleus4.geometry} material={nodes.Nucleus4.material} position={[0.548, 1.444, 0.416]} rotation={[-0.547, 0.894, 2.197]} />
      <mesh name="Nucleus5" geometry={nodes.Nucleus5.geometry} material={nodes.Nucleus5.material} position={[0.748, 1, -0.405]} rotation={[3.012, 1.414, -1.284]} />
      <mesh name="Nucleus1" geometry={nodes.Nucleus1.geometry} material={nodes.Nucleus1.material} position={[0.035, 1.278, -0.786]} rotation={[-2.802, 0.416, -1.298]} />
      <mesh name="Nucleus2" geometry={nodes.Nucleus2.geometry} material={nodes.Nucleus2.material} position={[-0.794, 0.863, -0.153]} rotation={[Math.PI, 1.305, 0.355]} />
      <mesh name="Vacuole_granules" geometry={nodes.Vacuole_granules.geometry} material={nodes.Vacuole_granules.material} position={[0.019, 0.992, 0.006]} rotation={[2.086, 1.003, 2.6]} />
      <mesh name="Nucleolus1" geometry={nodes.Nucleolus1.geometry} material={nodes.Nucleolus1.material} position={[0.035, 1.278, -0.786]} />
      <mesh name="Nucleolus2" geometry={nodes.Nucleolus2.geometry} material={nodes.Nucleolus2.material} position={[-0.794, 0.863, -0.153]} />
      <mesh name="Nucleolus3" geometry={nodes.Nucleolus3.geometry} material={nodes.Nucleolus3.material} position={[0.012, 1, 0.828]} />
      <mesh name="Nucleolus4" geometry={nodes.Nucleolus4.geometry} material={nodes.Nucleolus4.material} position={[0.548, 1.444, 0.416]} />
      <mesh name="Nucleolus5" geometry={nodes.Nucleolus5.geometry} material={nodes.Nucleolus5.material} position={[0.748, 1, -0.405]} />
      <mesh name="VacuoleMLO1" geometry={nodes.VacuoleMLO1.geometry} material={nodes.VacuoleMLO1.material} position={[-0.582, 0.912, 0.604]} rotation={[-0.507, -0.063, 0.548]} />
      <mesh name="VacuoleMLO2" geometry={nodes.VacuoleMLO2.geometry} material={nodes.VacuoleMLO2.material} position={[0.536, 0.912, 0.604]} rotation={[-0.22, 0.925, 1.41]} />
      <mesh name="VacuoleMLO3" geometry={nodes.VacuoleMLO3.geometry} material={nodes.VacuoleMLO3.material} position={[-0.313, 0.912, -0.761]} rotation={[-2.937, -1.187, -3.045]} />
    </group>
  )
}

useGLTF.preload('/models/BlastoCystisVacuole-v1.glb')
