/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/EColiCyst-v1.glb -o src/components/EntamoebaColi/Cyst/EColiCyst.jsx -k -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/EColiCyst-v1.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="inner_cyst_membrane001"
        geometry={nodes.inner_cyst_membrane001.geometry}
        material={nodes.inner_cyst_membrane001.material}
        position={[0, 0, -2.576]}
      />
      <mesh
        name="outer_cyst_membrane001"
        geometry={nodes.outer_cyst_membrane001.geometry}
        material={nodes.outer_cyst_membrane001.material}
        position={[0, 1, -2.576]}
      />
      <mesh
        name="chromatin_layer004"
        geometry={nodes.chromatin_layer004.geometry}
        material={nodes.chromatin_layer004.material}
        position={[0, 0.772, -2.033]}
      />
      <mesh
        name="chromatin_layer005"
        geometry={nodes.chromatin_layer005.geometry}
        material={nodes.chromatin_layer005.material}
        position={[0.094, 1.45, -2.305]}
      />
      <mesh
        name="chromatin_layer006"
        geometry={nodes.chromatin_layer006.geometry}
        material={nodes.chromatin_layer006.material}
        position={[0, 1.415, -3.053]}
      />
      <mesh
        name="chromatin_layer007"
        geometry={nodes.chromatin_layer007.geometry}
        material={nodes.chromatin_layer007.material}
        position={[0.015, 0.747, -3.004]}
      />
      <mesh
        name="karyosome004"
        geometry={nodes.karyosome004.geometry}
        material={nodes.karyosome004.material}
        position={[0, 0.706, -2.079]}
      />
      <mesh
        name="karyosome005"
        geometry={nodes.karyosome005.geometry}
        material={nodes.karyosome005.material}
        position={[0.094, 1.491, -2.367]}
      />
      <mesh
        name="karyosome006"
        geometry={nodes.karyosome006.geometry}
        material={nodes.karyosome006.material}
        position={[0, 1.365, -2.973]}
      />
      <mesh
        name="karyosome007"
        geometry={nodes.karyosome007.geometry}
        material={nodes.karyosome007.material}
        position={[0.015, 0.755, -2.954]}
      />
      <mesh
        name="nuclear_envelope004"
        geometry={nodes.nuclear_envelope004.geometry}
        material={nodes.nuclear_envelope004.material}
        position={[0, 0.772, -2.033]}
      />
      <mesh
        name="nuclear_envelope005"
        geometry={nodes.nuclear_envelope005.geometry}
        material={nodes.nuclear_envelope005.material}
        position={[0.094, 1.45, -2.305]}
      />
      <mesh
        name="nuclear_envelope006"
        geometry={nodes.nuclear_envelope006.geometry}
        material={nodes.nuclear_envelope006.material}
        position={[0, 1.415, -3.053]}
      />
      <mesh
        name="nuclear_envelope007"
        geometry={nodes.nuclear_envelope007.geometry}
        material={nodes.nuclear_envelope007.material}
        position={[0.015, 0.747, -3.004]}
      />
      <mesh
        name="Chromatoid1"
        geometry={nodes.Chromatoid1.geometry}
        material={nodes.Chromatoid1.material}
        position={[0.321, 0.974, -2.693]}
        rotation={[0.322, -0.051, -0.078]}
      />
      <mesh
        name="Chromatoid2"
        geometry={nodes.Chromatoid2.geometry}
        material={nodes.Chromatoid2.material}
        position={[0.321, 0.974, -2.38]}
        rotation={[-0.338, 0.156, 0.144]}
      />
      <mesh
        name="Chromatoid3"
        geometry={nodes.Chromatoid3.geometry}
        material={nodes.Chromatoid3.material}
        position={[0.28, 1.53, -2.43]}
        rotation={[-0.961, 0.36, 0.329]}
      />
      <mesh
        name="Chromatoid4"
        geometry={nodes.Chromatoid4.geometry}
        material={nodes.Chromatoid4.material}
        position={[-0.315, 1.214, -2.812]}
        rotation={[1.132, -0.121, 0.718]}
      />
      <mesh
        name="Glycogen"
        geometry={nodes.Glycogen.geometry}
        material={nodes.Glycogen.material}
        position={[0, 0.995, -2.576]}
      />
    </group>
  );
}

useGLTF.preload("/models/EColiCyst-v1.glb");
