/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Hartmannitrophozoitebody-v1.glb -o src/components/EntamoebaHartmanni/HartmanniBody.jsx -k -r public 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/Hartmannitrophozoitebody-v1.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="outermembrane" geometry={nodes.outermembrane.geometry} material={nodes.outermembrane.material} morphTargetDictionary={nodes.outermembrane.morphTargetDictionary} morphTargetInfluences={nodes.outermembrane.morphTargetInfluences} position={[0.124, 0.972, -0.651]} />
        <mesh name="innermembrane" geometry={nodes.innermembrane.geometry} material={nodes.innermembrane.material} morphTargetDictionary={nodes.innermembrane.morphTargetDictionary} morphTargetInfluences={nodes.innermembrane.morphTargetInfluences} position={[0.124, 0.972, -0.651]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Hartmannitrophozoitebody-v1.glb')
