/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/enthyst2-v1.glb -o src/components/Enthyst2.jsx -k -r public 
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations, useTexture } from "@react-three/drei";
import { useControls } from "leva";
import { BodyMaterial } from "./BodyMaterial";
import { Nucleus } from "./Nucleus";
import { CytoplasmParticles } from "./CytoplasmParticles";
import { FoodVacuoles } from "./FoodVacuoles";
import * as THREE from "three";
import { AnimatedBodyMaterial } from "./AnimatedBodyMaterial";
import { LavaCytoplasmMaterial } from "./CytoplasmVolumeMaterial";
import { GlassyCytoplasmMaterial } from "./glassyCytoplasmMaterial";
import { WarpedCytoplasmMaterial } from "./WarpedCytoplasmMaterial";
import { IQWarpedMaterial } from "./IQWarpedMaterial";

export function Model2(props) {
  const group = React.useRef();
  const { nodes, _materials, animations } = useGLTF("/models/enthyst2-v1.glb");
  const { actions } = useAnimations(animations, group);

  const cloudTexture = useTexture("/textures/lava/cloud.png");
  const lavaTexture = useTexture("/textures/lava/lavatile.jpg");

  useEffect(() => {
    cloudTexture.wrapS = cloudTexture.wrapT = THREE.RepeatWrapping;
    lavaTexture.wrapS = lavaTexture.wrapT = THREE.RepeatWrapping;
    lavaTexture.colorSpace = THREE.SRGBColorSpace;
  }, [cloudTexture, lavaTexture]);

  useEffect(() => {
    const action = actions?.["Cube.004Action"];
    console.log("Available actions:", actions);
    console.log("Chosen action:", action);

    if (action) {
      action.reset().fadeIn(0.5).play();
      console.log("Action started");
    }
  }, [actions]);

  const { nucleusposition, particlesPosition } = useControls({
    nucleusposition: {
      x: 0.08,
      y: 1.0,
      z: 0.05,
    },
    particlesPosition: {
      x: 0.03,
      y: 0.9,
      z: 0.09,
    },
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="enthyst2"
          geometry={nodes.enthyst2.geometry}
          morphTargetDictionary={nodes.enthyst2.morphTargetDictionary}
          morphTargetInfluences={nodes.enthyst2.morphTargetInfluences}
          position={[0, 0.839, 0]}
          castShadow
          receiveShadow
        >
          {/* <meshPhysicalMaterial
            color="#cfdcc8"
            transparent
            opacity={0.28}
            roughness={0.95}
            metalness={0}
            transmission={0}
            depthWrite={false}
          /> */}
          {/* <AnimatedBodyMaterial /> */}
          {/* <CytoplasmVolumeMaterial
            texture1={cloudTexture}
            texture2={lavaTexture}
            uvScale={new THREE.Vector2(3.0, 1.0)}
            alphaMin={0.5}
            alphaMax={0.95}
          /> */}
          {/* <LavaCytoplasmMaterial /> */}
          {/* <GlassyCytoplasmMaterial /> */}
          <WarpedCytoplasmMaterial />
          {/* <IQWarpedMaterial /> */}
        </mesh>

        <Nucleus
          position={[nucleusposition.x, nucleusposition.y, nucleusposition.z]}
        />

        <CytoplasmParticles
          position={[
            particlesPosition.x,
            particlesPosition.y,
            particlesPosition.z,
          ]}
        />

        <FoodVacuoles />
      </group>
    </group>
  );
}

useGLTF.preload("/models/enthyst2-v1.glb");
