/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/enthyst2-v1.glb -o src/components/Enthyst2.jsx -k -r public 
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useControls } from "leva";
import { BodyMaterial } from "./BodyMaterial";
import { Nucleus } from "./Nucleus";
import { CytoplasmParticles } from "./CytoplasmParticles";
import { FoodVacuoles } from "./FoodVacuoles";
import * as THREE from "three";
import { AnimatedBodyMaterial } from "./AnimatedBodyMaterial";

export function Model2(props) {
  const group = React.useRef();
  const { nodes, _materials, animations } = useGLTF("/models/enthyst2-v1.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    const action = actions?.["Cube.004Action"];
    console.log("Available actions:", actions);
    console.log("Chosen action:", action);

    if (action) {
      action.reset().fadeIn(0.5).play();
      console.log("Action started");
    }
  }, [actions]);

  const { nucleusposition, particlesPosition } = useControls({
    nucleusposition: {
      x: 0.08,
      y: 1.0,
      z: 0.05,
    },
    particlesPosition: {
      x: -0.03,
      y: 0.9,
      z: -0.16,
    },
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="enthyst2"
          geometry={nodes.enthyst2.geometry}
          morphTargetDictionary={nodes.enthyst2.morphTargetDictionary}
          morphTargetInfluences={nodes.enthyst2.morphTargetInfluences}
          position={[0, 0.839, 0]}
          castShadow
          receiveShadow
        >
          {/* <meshPhysicalMaterial
            color="#cfdcc8"
            transparent
            opacity={0.28}
            roughness={0.95}
            metalness={0}
            transmission={0}
            depthWrite={false}
          /> */}
          <AnimatedBodyMaterial />
        </mesh>

        <Nucleus
          position={[nucleusposition.x, nucleusposition.y, nucleusposition.z]}
        />

        <CytoplasmParticles
          position={[
            particlesPosition.x,
            particlesPosition.y,
            particlesPosition.z,
          ]}
        />

        <FoodVacuoles />
      </group>
    </group>
  );
}

useGLTF.preload("/models/enthyst2-v1.glb");
