/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/GardiaLambliaCyst-v1.glb -o src/components/GiardiaLamblia/Cyst/GLCyst.jsx -k -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/GardiaLambliaCyst-v1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="fibril5" geometry={nodes.fibril5.geometry} material={nodes.fibril5.material} position={[0.076, 1.691, 2.652]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="fibril8" geometry={nodes.fibril8.geometry} material={nodes.fibril8.material} position={[0.077, 1.691, 2.76]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="fibril2" geometry={nodes.fibril2.geometry} material={nodes.fibril2.material} position={[0.077, 1.697, 2.543]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="fibril17" geometry={nodes.fibril17.geometry} material={nodes.fibril17.material} position={[-0.014, 1.699, 2.768]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="fibril1" geometry={nodes.fibril1.geometry} material={nodes.fibril1.material} position={[0, 1.694, 2.491]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="fibril3" geometry={nodes.fibril3.geometry} material={nodes.fibril3.material} position={[-0.015, 1.7, 2.572]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="fibril4" geometry={nodes.fibril4.geometry} material={nodes.fibril4.material} position={[-0.025, 1.695, 2.634]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="fibril6" geometry={nodes.fibril6.geometry} material={nodes.fibril6.material} position={[-0.039, 1.7, 2.696]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="medianbody2001" geometry={nodes.medianbody2001.geometry} material={nodes.medianbody2001.material} position={[0, 1.381, 2.359]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="medianbody2002" geometry={nodes.medianbody2002.geometry} material={nodes.medianbody2002.material} position={[0, 1.381, 2.88]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      <mesh name="cystkaryosome1" geometry={nodes.cystkaryosome1.geometry} material={nodes.cystkaryosome1.material} position={[0, 2.898, 2.321]} />
      <mesh name="cystkaryosome2" geometry={nodes.cystkaryosome2.geometry} material={nodes.cystkaryosome2.material} position={[0, 2.452, 2.321]} />
      <mesh name="cystkaryosome3" geometry={nodes.cystkaryosome3.geometry} material={nodes.cystkaryosome3.material} position={[0, 2.898, 3.021]} />
      <mesh name="cystkaryosome4" geometry={nodes.cystkaryosome4.geometry} material={nodes.cystkaryosome4.material} position={[0, 2.452, 3.021]} />
      <mesh name="cystnucleus1" geometry={nodes.cystnucleus1.geometry} material={nodes.cystnucleus1.material} position={[0, 2.898, 2.321]} />
      <mesh name="cystnucleus2" geometry={nodes.cystnucleus2.geometry} material={nodes.cystnucleus2.material} position={[0, 2.452, 2.321]} />
      <mesh name="cystnucleus3" geometry={nodes.cystnucleus3.geometry} material={nodes.cystnucleus3.material} position={[0, 2.898, 3.021]} />
      <mesh name="cystnucleus4" geometry={nodes.cystnucleus4.geometry} material={nodes.cystnucleus4.material} position={[0, 2.452, 3.021]} />
      <mesh name="cystwall" geometry={nodes.cystwall.geometry} material={nodes.cystwall.material} position={[0, 2.149, 2.638]} />
      <mesh name="protoplast" geometry={nodes.protoplast.geometry} material={nodes.protoplast.material} position={[0, 2.149, 2.638]} />
    </group>
  )
}

useGLTF.preload('/models/GardiaLambliaCyst-v1.glb')
