/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CryptosporidiumsppOocyst-v1.glb -o src/components/CryptoSporidium/CryptoSprodiumOocyst.jsx -k -r public 
*/

import React, { useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import OocystBodyMaterial from "./shaders/OocystCryptoBodyShader";
import { createCryptoMaterials } from "./shaders/CryptoMaterials";

export function CryptoSporidiumOocyst(props) {
  const { nodes, materials } = useGLTF(
    "/models/CryptosporidiumsppOocyst-v1.glb",
  );

  const {
    residualBodyMaterial,
    sporozoiteMaterial,
    conoidMaterial,
    rhoptryMaterial,
    micronemeMaterial,
    nucleusMaterial,
    mitosomeMaterial,
  } = useMemo(() => createCryptoMaterials(), []);
  return (
    <group {...props} dispose={null}>
      <mesh
        name="oocystbody"
        geometry={nodes.oocystbody.geometry}
        material={nodes.oocystbody.material}
        position={[0, 1, 0]}
      >
        <OocystBodyMaterial
          opacity={0.42}
          baseColor="#709a31"
          shadowColor="#1f2f0d"
          wallTint="#46570b"
          noiseScale={14.6}
          flowSpeed={10.08}
          brightness={0.01}
          wallStrength={1.74}
          granuleStrength={2.06}
          fresnelStrength={0.0}
          wobbleStrength={0.044}
          wobbleSpeed={1.42}
        />
        {/* <meshStandardMaterial color="#cccccc" roughness={0.9} metalness={0} /> */}
      </mesh>
      <mesh
        name="ResidualboDY"
        geometry={nodes.ResidualboDY.geometry}
        material={residualBodyMaterial}
        position={[0.099, 0.844, -0.196]}
        rotation={[-0.968, -0.453, -Math.PI / 2]}
        scale={0.07}
      />

      {/* Sporozoites */}
      <mesh
        name="Sporozoite1"
        geometry={nodes.Sporozoite1.geometry}
        material={sporozoiteMaterial}
        position={[-0.116, 1.152, -0.489]}
        rotation={[-3.064, -0.743, -0.381]}
        scale={0.519}
      />
      <mesh
        name="Sporozoite1001"
        geometry={nodes.Sporozoite1001.geometry}
        material={sporozoiteMaterial}
        position={[0.456, 0.823, -0.017]}
        rotation={[1.28, 0.004, 0.026]}
        scale={0.519}
      />
      <mesh
        name="Sporozoite1002"
        geometry={nodes.Sporozoite1002.geometry}
        material={sporozoiteMaterial}
        position={[-0.007, 1.329, 0.359]}
        rotation={[-0.482, -0.227, -2.688]}
        scale={0.519}
      />
      <mesh
        name="Sporozoite1003"
        geometry={nodes.Sporozoite1003.geometry}
        material={sporozoiteMaterial}
        position={[-0.357, 1.264, -0.06]}
        rotation={[-0.313, -1.162, 2.824]}
        scale={0.519}
      />

      {/* Conoids */}
      <mesh
        name="Conoid1"
        geometry={nodes.Conoid1.geometry}
        material={conoidMaterial}
        position={[-0.139, 1.429, -0.281]}
        rotation={[1.194, 0.327, -0.108]}
        scale={[0.027, 0.042, 0.027]}
      />
      <mesh
        name="Conoid1001"
        geometry={nodes.Conoid1001.geometry}
        material={conoidMaterial}
        position={[0.441, 0.847, -0.363]}
        rotation={[-0.89, -0.389, 0.324]}
        scale={[0.027, 0.042, 0.027]}
      />
      <mesh
        name="Conoid1002"
        geometry={nodes.Conoid1002.geometry}
        material={conoidMaterial}
        position={[-0.097, 1.529, 0.09]}
        rotation={[1.68, 0.864, -2.887]}
        scale={[0.027, 0.042, 0.027]}
      />
      <mesh
        name="Conoid1003"
        geometry={nodes.Conoid1003.geometry}
        material={conoidMaterial}
        position={[-0.196, 1.57, -0.091]}
        rotation={[1.396, 0.546, -1.478]}
        scale={[0.027, 0.042, 0.027]}
      />

      {/* Rhoptries */}
      <mesh
        name="Rhoptries2"
        geometry={nodes.Rhoptries2.geometry}
        material={rhoptryMaterial}
        position={[-0.197, 1.394, -0.334]}
        rotation={[0.999, 0.042, -0.076]}
        scale={[0.022, 0.033, 0.022]}
      />
      <mesh
        name="Rhoptries1"
        geometry={nodes.Rhoptries1.geometry}
        material={rhoptryMaterial}
        position={[-0.135, 1.391, -0.406]}
        rotation={[0.999, 0.042, -0.076]}
        scale={[0.022, 0.033, 0.022]}
      />
      <mesh
        name="Rhoptries2001"
        geometry={nodes.Rhoptries2001.geometry}
        material={rhoptryMaterial}
        position={[0.418, 0.783, -0.31]}
        rotation={[-0.971, -0.726, 0.277]}
        scale={[0.022, 0.033, 0.022]}
      />
      <mesh
        name="Rhoptries1001"
        geometry={nodes.Rhoptries1001.geometry}
        material={rhoptryMaterial}
        position={[0.5, 0.786, -0.264]}
        rotation={[-0.971, -0.726, 0.277]}
        scale={[0.022, 0.033, 0.022]}
      />
      <mesh
        name="Rhoptries2002"
        geometry={nodes.Rhoptries2002.geometry}
        material={rhoptryMaterial}
        position={[-0.081, 1.549, 0.172]}
        rotation={[1.905, 1.189, -3.086]}
        scale={[0.022, 0.033, 0.022]}
      />
      <mesh
        name="Rhoptries1002"
        geometry={nodes.Rhoptries1002.geometry}
        material={rhoptryMaterial}
        position={[-0.138, 1.482, 0.205]}
        rotation={[1.905, 1.189, -3.086]}
        scale={[0.022, 0.033, 0.022]}
      />
      <mesh
        name="Rhoptries2003"
        geometry={nodes.Rhoptries2003.geometry}
        material={rhoptryMaterial}
        position={[-0.262, 1.546, -0.041]}
        rotation={[0.999, 0.649, -1.257]}
        scale={[0.022, 0.033, 0.022]}
      />
      <mesh
        name="Rhoptries1003"
        geometry={nodes.Rhoptries1003.geometry}
        material={rhoptryMaterial}
        position={[-0.308, 1.507, -0.113]}
        rotation={[0.999, 0.649, -1.257]}
        scale={[0.022, 0.033, 0.022]}
      />

      {/* Nuclei */}
      <mesh
        name="Nucleus1"
        geometry={nodes.Nucleus1.geometry}
        material={nucleusMaterial}
        position={[-0.116, 1.16, -0.601]}
        rotation={[0.325, 0.08, 0.003]}
        scale={[0.066, 0.086, 0.066]}
      />
      <mesh
        name="Nucleus1001"
        geometry={nodes.Nucleus1001.geometry}
        material={nucleusMaterial}
        position={[0.527, 0.753, 0.036]}
        rotation={[-1.876, -0.703, -0.304]}
        scale={[0.066, 0.086, 0.066]}
      />
      <mesh
        name="Nucleus1002"
        geometry={nodes.Nucleus1002.geometry}
        material={nucleusMaterial}
        position={[-0.075, 1.31, 0.446]}
        rotation={[3.082, 0.83, 2.191]}
        scale={[0.066, 0.086, 0.066]}
      />
      <mesh
        name="Nucleus1003"
        geometry={nodes.Nucleus1003.geometry}
        material={nucleusMaterial}
        position={[-0.463, 1.247, -0.094]}
        rotation={[0.367, 1.237, -0.681]}
        scale={[0.066, 0.086, 0.066]}
      />

      {/* Mitosomes */}
      <mesh
        name="Mitosome1"
        geometry={nodes.Mitosome1.geometry}
        material={mitosomeMaterial}
        position={[-0.116, 1.152, -0.489]}
        rotation={[-0.157, -0.061, -1.483]}
        scale={0.024}
      />
      <mesh
        name="Mitosome1001"
        geometry={nodes.Mitosome1001.geometry}
        material={mitosomeMaterial}
        position={[0.456, 0.823, -0.017]}
        rotation={[-2.492, -0.589, -2.174]}
        scale={0.024}
      />
      <mesh
        name="Mitosome1002"
        geometry={nodes.Mitosome1002.geometry}
        material={mitosomeMaterial}
        position={[-0.007, 1.329, 0.359]}
        rotation={[-2.77, 0.46, 0.433]}
        scale={0.024}
      />
      <mesh
        name="Mitosome1003"
        geometry={nodes.Mitosome1003.geometry}
        material={mitosomeMaterial}
        position={[-0.357, 1.264, -0.06]}
        rotation={[-0.965, 1.1, -0.918]}
        scale={0.024}
      />

      {/* Micronemes — apply same material to all Microneme* meshes */}
      <mesh
        name="Microneme12"
        geometry={nodes.Microneme12.geometry}
        material={micronemeMaterial}
        position={[-0.157, 1.303, -0.56]}
        scale={0.018}
      />
      <mesh
        name="Microneme1"
        geometry={nodes.Microneme1.geometry}
        material={micronemeMaterial}
        position={[-0.133, 1.339, -0.492]}
        scale={0.021}
      />
      <mesh
        name="Microneme6"
        geometry={nodes.Microneme6.geometry}
        material={micronemeMaterial}
        position={[-0.127, 1.047, -0.635]}
        scale={0.019}
      />
      <mesh
        name="Microneme5"
        geometry={nodes.Microneme5.geometry}
        material={micronemeMaterial}
        position={[-0.106, 0.97, -0.527]}
        scale={0.017}
      />
      <mesh
        name="Microneme8"
        geometry={nodes.Microneme8.geometry}
        material={micronemeMaterial}
        position={[-0.115, 0.887, -0.647]}
        scale={0.021}
      />
      <mesh
        name="Microneme9"
        geometry={nodes.Microneme9.geometry}
        material={micronemeMaterial}
        position={[0, 0.828, -0.521]}
        scale={0.013}
      />
      <mesh
        name="Microneme7"
        geometry={nodes.Microneme7.geometry}
        material={micronemeMaterial}
        position={[-0.016, 0.996, -0.609]}
        scale={0.02}
      />
      <mesh
        name="Microneme4"
        geometry={nodes.Microneme4.geometry}
        material={micronemeMaterial}
        position={[-0.13, 1.248, -0.529]}
        scale={0.018}
      />
      <mesh
        name="Microneme3"
        geometry={nodes.Microneme3.geometry}
        material={micronemeMaterial}
        position={[-0.1, 1.304, -0.437]}
        scale={0.021}
      />
      <mesh
        name="Microneme2"
        geometry={nodes.Microneme2.geometry}
        material={micronemeMaterial}
        position={[-0.174, 1.446, -0.421]}
        scale={0.018}
      />
      <mesh
        name="Microneme10"
        geometry={nodes.Microneme10.geometry}
        material={micronemeMaterial}
        position={[0, 0.898, -0.531]}
        scale={0.013}
      />
      <mesh
        name="Microneme11"
        geometry={nodes.Microneme11.geometry}
        material={micronemeMaterial}
        position={[0.033, 0.827, -0.576]}
        scale={0.013}
      />

      <mesh
        name="Microneme12001"
        geometry={nodes.Microneme12001.geometry}
        material={micronemeMaterial}
        position={[0.537, 0.704, -0.11]}
        rotation={[-2.294, -0.634, -0.581]}
        scale={0.018}
      />
      <mesh
        name="Microneme1001"
        geometry={nodes.Microneme1001.geometry}
        material={micronemeMaterial}
        position={[0.53, 0.751, -0.174]}
        rotation={[-2.294, -0.634, -0.581]}
        scale={0.021}
      />
      <mesh
        name="Microneme6001"
        geometry={nodes.Microneme6001.geometry}
        material={micronemeMaterial}
        position={[0.489, 0.76, 0.148]}
        rotation={[-2.294, -0.634, -0.581]}
        scale={0.019}
      />
      <mesh
        name="Microneme5001"
        geometry={nodes.Microneme5001.geometry}
        material={micronemeMaterial}
        position={[0.405, 0.864, 0.158]}
        rotation={[-2.294, -0.634, -0.581]}
        scale={0.017}
      />
      <mesh
        name="Microneme8001"
        geometry={nodes.Microneme8001.geometry}
        material={micronemeMaterial}
        position={[0.433, 0.81, 0.291]}
        rotation={[-2.294, -0.634, -0.581]}
        scale={0.021}
      />
      <mesh
        name="Microneme9001"
        geometry={nodes.Microneme9001.geometry}
        material={micronemeMaterial}
        position={[0.41, 0.989, 0.283]}
        rotation={[-2.294, -0.634, -0.581]}
        scale={0.013}
      />
      <mesh
        name="Microneme7001"
        geometry={nodes.Microneme7001.geometry}
        material={micronemeMaterial}
        position={[0.526, 0.872, 0.186]}
        rotation={[-2.294, -0.634, -0.581]}
        scale={0.02}
      />
      <mesh
        name="Microneme4001"
        geometry={nodes.Microneme4001.geometry}
        material={micronemeMaterial}
        position={[0.513, 0.759, -0.077]}
        rotation={[-2.294, -0.634, -0.581]}
        scale={0.018}
      />
      <mesh
        name="Microneme3001"
        geometry={nodes.Microneme3001.geometry}
        material={micronemeMaterial}
        position={[0.504, 0.819, -0.171]}
        rotation={[-2.294, -0.634, -0.581]}
        scale={0.021}
      />
      <mesh
        name="Microneme2001"
        geometry={nodes.Microneme2001.geometry}
        material={micronemeMaterial}
        position={[0.507, 0.731, -0.305]}
        rotation={[-2.294, -0.634, -0.581]}
        scale={0.018}
      />
      <mesh
        name="Microneme10001"
        geometry={nodes.Microneme10001.geometry}
        material={micronemeMaterial}
        position={[0.447, 0.962, 0.229]}
        rotation={[-2.294, -0.634, -0.581]}
        scale={0.013}
      />
      <mesh
        name="Microneme11001"
        geometry={nodes.Microneme11001.geometry}
        material={micronemeMaterial}
        position={[0.464, 0.981, 0.315]}
        rotation={[-2.294, -0.634, -0.581]}
        scale={0.013}
      />

      <mesh
        name="Microneme12002"
        geometry={nodes.Microneme12002.geometry}
        material={micronemeMaterial}
        position={[-0.148, 1.425, 0.374]}
        rotation={[-2.902, 0.584, 1.978]}
        scale={0.018}
      />
      <mesh
        name="Microneme1002"
        geometry={nodes.Microneme1002.geometry}
        material={micronemeMaterial}
        position={[-0.147, 1.437, 0.294]}
        rotation={[-2.902, 0.584, 1.978]}
        scale={0.021}
      />
      <mesh
        name="Microneme6002"
        geometry={nodes.Microneme6002.geometry}
        material={micronemeMaterial}
        position={[-0.003, 1.256, 0.523]}
        rotation={[-2.902, 0.584, 1.978]}
        scale={0.019}
      />
      <mesh
        name="Microneme5002"
        geometry={nodes.Microneme5002.geometry}
        material={micronemeMaterial}
        position={[0.109, 1.221, 0.458]}
        rotation={[-2.902, 0.584, 1.978]}
        scale={0.017}
      />
      <mesh
        name="Microneme8002"
        geometry={nodes.Microneme8002.geometry}
        material={micronemeMaterial}
        position={[0.109, 1.163, 0.592]}
        rotation={[-2.902, 0.584, 1.978]}
        scale={0.021}
      />
      <mesh
        name="Microneme9002"
        geometry={nodes.Microneme9002.geometry}
        material={micronemeMaterial}
        position={[0.186, 1.061, 0.464]}
        rotation={[-2.902, 0.584, 1.978]}
        scale={0.013}
      />
      <mesh
        name="Microneme7002"
        geometry={nodes.Microneme7002.geometry}
        material={micronemeMaterial}
        position={[0.013, 1.142, 0.475]}
        rotation={[-2.902, 0.584, 1.978]}
        scale={0.02}
      />
      <mesh
        name="Microneme4002"
        geometry={nodes.Microneme4002.geometry}
        material={micronemeMaterial}
        position={[-0.098, 1.381, 0.359]}
        rotation={[-2.902, 0.584, 1.978]}
        scale={0.018}
      />
      <mesh
        name="Microneme3002"
        geometry={nodes.Microneme3002.geometry}
        material={micronemeMaterial}
        position={[-0.1, 1.402, 0.249]}
        rotation={[-2.902, 0.584, 1.978]}
        scale={0.021}
      />
      <mesh
        name="Microneme2002"
        geometry={nodes.Microneme2002.geometry}
        material={micronemeMaterial}
        position={[-0.175, 1.539, 0.212]}
        rotation={[-2.902, 0.584, 1.978]}
        scale={0.018}
      />
      <mesh
        name="Microneme10002"
        geometry={nodes.Microneme10002.geometry}
        material={micronemeMaterial}
        position={[0.127, 1.095, 0.444]}
        rotation={[-2.902, 0.584, 1.978]}
        scale={0.013}
      />
      <mesh
        name="Microneme11002"
        geometry={nodes.Microneme11002.geometry}
        material={micronemeMaterial}
        position={[0.145, 1.022, 0.494]}
        rotation={[-2.902, 0.584, 1.978]}
        scale={0.013}
      />

      <mesh
        name="Microneme12003"
        geometry={nodes.Microneme12003.geometry}
        material={micronemeMaterial}
        position={[-0.452, 1.401, -0.101]}
        rotation={[-0.67, 1.221, 0.29]}
        scale={0.018}
      />
      <mesh
        name="Microneme1003"
        geometry={nodes.Microneme1003.geometry}
        material={micronemeMaterial}
        position={[-0.384, 1.441, -0.119]}
        rotation={[-0.67, 1.221, 0.29]}
        scale={0.021}
      />
      <mesh
        name="Microneme6003"
        geometry={nodes.Microneme6003.geometry}
        material={micronemeMaterial}
        position={[-0.487, 1.14, -0.05]}
        rotation={[-0.67, 1.221, 0.29]}
        scale={0.019}
      />
      <mesh
        name="Microneme5003"
        geometry={nodes.Microneme5003.geometry}
        material={micronemeMaterial}
        position={[-0.371, 1.085, -0.009]}
        rotation={[-0.67, 1.221, 0.29]}
        scale={0.017}
      />
      <mesh
        name="Microneme8003"
        geometry={nodes.Microneme8003.geometry}
        material={micronemeMaterial}
        position={[-0.479, 0.986, -0.002]}
        rotation={[-0.67, 1.221, 0.29]}
        scale={0.021}
      />
      <mesh
        name="Microneme9003"
        geometry={nodes.Microneme9003.geometry}
        material={micronemeMaterial}
        position={[-0.317, 0.921, -0.047]}
        rotation={[-0.67, 1.221, 0.29]}
        scale={0.013}
      />
      <mesh
        name="Microneme7003"
        geometry={nodes.Microneme7003.geometry}
        material={micronemeMaterial}
        position={[-0.421, 1.062, -0.121]}
        rotation={[-0.67, 1.221, 0.29]}
        scale={0.02}
      />
      <mesh
        name="Microneme4003"
        geometry={nodes.Microneme4003.geometry}
        material={micronemeMaterial}
        position={[-0.409, 1.348, -0.096]}
        rotation={[-0.67, 1.221, 0.29]}
        scale={0.018}
      />
      <mesh
        name="Microneme3003"
        geometry={nodes.Microneme3003.geometry}
        material={micronemeMaterial}
        position={[-0.318, 1.409, -0.119]}
        rotation={[-0.67, 1.221, 0.29]}
        scale={0.021}
      />
      <mesh
        name="Microneme2003"
        geometry={nodes.Microneme2003.geometry}
        material={micronemeMaterial}
        position={[-0.341, 1.567, -0.104]}
        rotation={[-0.67, 1.221, 0.29]}
        scale={0.018}
      />
      <mesh
        name="Microneme10003"
        geometry={nodes.Microneme10003.geometry}
        material={micronemeMaterial}
        position={[-0.333, 0.983, -0.076]}
        rotation={[-0.67, 1.221, 0.29]}
        scale={0.013}
      />
      <mesh
        name="Microneme11003"
        geometry={nodes.Microneme11003.geometry}
        material={micronemeMaterial}
        position={[-0.358, 0.897, -0.09]}
        rotation={[-0.67, 1.221, 0.29]}
        scale={0.013}
      />
    </group>
  );
}

useGLTF.preload("/models/CryptosporidiumsppOocyst-v1.glb");
