/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CystoisosporabelliOocyst-v1.glb -o src/components/CystoisosporaBelli/CystoisosporaBelliOocyst.jsx -k -r public 
*/

import React, { useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import CBOocystBodyMaterial from "./shaders/CBOocystBodyMaterial";
import { createCBMaterials } from "./shaders/CBMaterials";

export function CBOocyst(props) {
  const { nodes, materials } = useGLTF(
    "/models/CystoisosporabelliOocyst-v1.glb",
  );
  const {
    sporocystMaterial,
    sporozoiteMaterial,
    nucleusMaterial,
    residualBodyMaterial,
  } = useMemo(() => createCBMaterials(), []);
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Oocyst"
        geometry={nodes.Oocyst.geometry}
        material={nodes.Oocyst.material}
        position={[0, 1, 0]}
      >
        <CBOocystBodyMaterial
          opacity={0.84}
          baseColor="#d3e2b3"
          shadowColor="#5a970e"
          wallTint="#252d0a"
          noiseScale={13.8}
          flowSpeed={10.04}
          brightness={0.0}
          wallStrength={0.72}
          granuleStrength={0.03}
          fresnelStrength={0.0}
          wobbleStrength={0.032}
          wobbleSpeed={0.84}
        />
      </mesh>
      <mesh
        name="Sporocyst1"
        geometry={nodes.Sporocyst1.geometry}
        material={sporocystMaterial}
        position={[0, 1, 0.448]}
      />
      <mesh
        name="Sporocyst2"
        geometry={nodes.Sporocyst2.geometry}
        material={sporocystMaterial}
        position={[-0.003, 0.996, -0.57]}
        rotation={[-0.355, -0.079, -0.061]}
      />

      <mesh
        name="Sporozoite1"
        geometry={nodes.Sporozoite1.geometry}
        material={sporozoiteMaterial}
        position={[-0.014, 1.093, 0.678]}
        rotation={[-0.113, -0.068, -2.63]}
      />
      <mesh
        name="Sporozoite1001"
        geometry={nodes.Sporozoite1001.geometry}
        material={sporozoiteMaterial}
        position={[0.003, 1.106, 0.404]}
        rotation={[2.715, -0.708, -0.199]}
      />
      <mesh
        name="Sporozoite1002"
        geometry={nodes.Sporozoite1002.geometry}
        material={sporozoiteMaterial}
        position={[-0.046, 0.729, 0.398]}
        rotation={[-2.763, 0.945, -2.177]}
      />
      <mesh
        name="Sporozoite1003"
        geometry={nodes.Sporozoite1003.geometry}
        material={sporozoiteMaterial}
        position={[-0.149, 1.35, 0.398]}
        rotation={[-2.182, 0.321, -3.074]}
      />
      <mesh
        name="Sporozoite1004"
        geometry={nodes.Sporozoite1004.geometry}
        material={sporozoiteMaterial}
        position={[-0.029, 1.163, -0.389]}
        rotation={[-0.473, -0.14, -2.7]}
      />
      <mesh
        name="Sporozoite1005"
        geometry={nodes.Sporozoite1005.geometry}
        material={sporozoiteMaterial}
        position={[0.19, 1.079, -0.643]}
        rotation={[2.507, -0.673, -0.224]}
      />
      <mesh
        name="Sporozoite1006"
        geometry={nodes.Sporozoite1006.geometry}
        material={sporozoiteMaterial}
        position={[0.296, 0.815, -0.542]}
        rotation={[3.122, 1.041, -2.124]}
      />
      <mesh
        name="Sporozoite1007"
        geometry={nodes.Sporozoite1007.geometry}
        material={sporozoiteMaterial}
        position={[-0.126, 1.311, -0.751]}
        rotation={[-2.523, 0.416, -3.107]}
      />

      <mesh
        name="nucleus1"
        geometry={nodes.nucleus1.geometry}
        material={nucleusMaterial}
        position={[-0.011, 1.066, 0.756]}
        rotation={[0.362, 0.168, -0.022]}
      />
      <mesh
        name="nucleus1001"
        geometry={nodes.nucleus1001.geometry}
        material={nucleusMaterial}
        position={[-0.028, 1.054, 0.36]}
        rotation={[2.128, -0.488, 2.094]}
      />
      <mesh
        name="nucleus1002"
        geometry={nodes.nucleus1002.geometry}
        material={nucleusMaterial}
        position={[0.021, 0.762, 0.386]}
        rotation={[-1.726, 1.207, -0.483]}
      />
      <mesh
        name="nucleus1003"
        geometry={nodes.nucleus1003.geometry}
        material={nucleusMaterial}
        position={[-0.136, 1.423, 0.386]}
        rotation={[-1.628, 0.286, -0.611]}
      />
      <mesh
        name="nucleus1004"
        geometry={nodes.nucleus1004.geometry}
        material={nucleusMaterial}
        position={[-0.034, 1.165, -0.306]}
        rotation={[0.012, 0.072, -0.05]}
      />
      <mesh
        name="nucleus1005"
        geometry={nodes.nucleus1005.geometry}
        material={nucleusMaterial}
        position={[0.162, 1.018, -0.677]}
        rotation={[1.938, -0.448, 2.098]}
      />
      <mesh
        name="nucleus1006"
        geometry={nodes.nucleus1006.geometry}
        material={nucleusMaterial}
        position={[0.365, 0.84, -0.451]}
        rotation={[-1.856, 1.271, -0.718]}
      />
      <mesh
        name="nucleus1007"
        geometry={nodes.nucleus1007.geometry}
        material={nucleusMaterial}
        position={[-0.107, 1.375, -0.785]}
        rotation={[-1.956, 0.35, -0.692]}
      />

      <mesh
        name="ResidualboDY"
        geometry={nodes.ResidualboDY.geometry}
        material={residualBodyMaterial}
        position={[0.191, 0.852, 0.298]}
        rotation={[-0.968, -0.453, -Math.PI / 2]}
      />
      <mesh
        name="ResidualboDY001"
        geometry={nodes.ResidualboDY001.geometry}
        material={residualBodyMaterial}
        position={[-0.211, 0.852, -0.725]}
        rotation={[-0.968, -0.453, -Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload("/models/CystoisosporabelliOocyst-v1.glb");
